"""reports: add content_json snapshot column

Revision ID: 50a8a1cafafb
Revises: f256aefb2368
Create Date: 2026-08-22 16:23:11.091990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50a8a1cafafb'
down_revision: Union[str, None] = 'f256aefb2368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'content_json')
    # ### end Alembic commands ###
