"""entity model: cases, entities, relationships, provenance

Revision ID: 876722347ec0
Revises: 0002
Create Date: 2026-08-22 01:09:31.453932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876722347ec0'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('case_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cases_status', 'cases', ['status'], unique=False)
    op.create_index('idx_cases_user_id', 'cases', ['user_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entities_case_id', 'entities', ['case_id'], unique=False)
    op.create_index('idx_entities_entity_type', 'entities', ['entity_type'], unique=False)
    op.create_table('account_details',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('asset_details',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_value', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('contact_details',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('entity_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_media_entity_id', 'entity_media', ['entity_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_case_id', 'events', ['case_id'], unique=False)
    op.create_index('idx_events_entity_id', 'events', ['entity_id'], unique=False)
    op.create_index('idx_events_event_date', 'events', ['event_date'], unique=False)
    op.create_table('field_provenance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('source_module', sa.String(length=100), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_by', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['retrieved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_field_provenance_entity_field', 'field_provenance', ['entity_id', 'field_name'], unique=False)
    op.create_index('idx_field_provenance_entity_id', 'field_provenance', ['entity_id'], unique=False)
    op.create_table('legal_entity_details',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=500), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('director_name', sa.String(length=255), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('statutory_capital', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('location_details',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('person_details',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('patronymic', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passport_number', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_relationships_source_entity_id', 'relationships', ['source_entity_id'], unique=False)
    op.create_index('idx_relationships_target_entity_id', 'relationships', ['target_entity_id'], unique=False)
    op.create_table('vehicle_details',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_details')
    op.drop_index('idx_relationships_target_entity_id', table_name='relationships')
    op.drop_index('idx_relationships_source_entity_id', table_name='relationships')
    op.drop_table('relationships')
    op.drop_table('person_details')
    op.drop_table('location_details')
    op.drop_table('legal_entity_details')
    op.drop_index('idx_field_provenance_entity_id', table_name='field_provenance')
    op.drop_index('idx_field_provenance_entity_field', table_name='field_provenance')
    op.drop_table('field_provenance')
    op.drop_index('idx_events_event_date', table_name='events')
    op.drop_index('idx_events_entity_id', table_name='events')
    op.drop_index('idx_events_case_id', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_entity_media_entity_id', table_name='entity_media')
    op.drop_table('entity_media')
    op.drop_table('contact_details')
    op.drop_table('asset_details')
    op.drop_table('account_details')
    op.drop_index('idx_entities_entity_type', table_name='entities')
    op.drop_index('idx_entities_case_id', table_name='entities')
    op.drop_table('entities')
    op.drop_index('idx_cases_user_id', table_name='cases')
    op.drop_index('idx_cases_status', table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
